// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BigTitle: typeof import('./../components/BigTitle.vue')['default']
    Child: typeof import('./../components/Child.vue')['default']
    Css: typeof import('./../components/tutor/tab/Css.vue')['default']
    CssDemo: typeof import('./../components/CssDemo.vue')['default']
    DogListOne: typeof import('./../components/vuex-demo/dogs/DogListOne.vue')['default']
    DogListTwo: typeof import('./../components/vuex-demo/dogs/DogListTwo.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Father: typeof import('./../components/Father.vue')['default']
    Friend: typeof import('./../components/provide/Friend.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Html: typeof import('./../components/tutor/tab/Html.vue')['default']
    Javascript: typeof import('./../components/tutor/tab/Javascript.vue')['default']
    Markdown: typeof import('./../components/Markdown.vue')['default']
    Music: typeof import('./../components/Music.vue')['default']
    NeteaseSearch: typeof import('./../components/netease/NeteaseSearch.vue')['default']
    Parent: typeof import('./../components/provide/Parent.vue')['default']
    PetName: typeof import('./../components/model/PetName.vue')['default']
    Pictures: typeof import('./../components/Pictures.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShopsList: typeof import('./../components/tutor/ShopsList.vue')['default']
    Sun: typeof import('./../components/provide/Sun.vue')['default']
    Swiper: typeof import('./../components/Swiper.vue')['default']
    Tabs: typeof import('./../components/tutor/Tabs.vue')['default']
    TodoTList: typeof import('./../components/tutor/TodoTList.vue')['default']
    Weather: typeof import('./../components/Weather.vue')['default']
  }
}
