export const departments = {
  code: 0,
  msg: "操作成功",
  data: [
    {
      id: 2,
      orgId: null,
      pid: 0,
      name: "天帷信息技术（上海）股份有限公司",
      orgName: null,
      children: [
        {
          id: 1,
          orgId: null,
          pid: 2,
          name: "合肥天帷信息安全技术有限公司",
          orgName: null,
          children: [
            {
              id: 4,
              orgId: null,
              pid: 1,
              name: "技术部",
              orgName: null,
              children: [
                {
                  id: 19,
                  orgId: null,
                  pid: 4,
                  name: "测评一部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 20,
                  orgId: null,
                  pid: 4,
                  name: "测评二部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 21,
                  orgId: null,
                  pid: 4,
                  name: "测评三部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 22,
                  orgId: null,
                  pid: 4,
                  name: "测评四部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 23,
                  orgId: null,
                  pid: 4,
                  name: "测评五部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 24,
                  orgId: null,
                  pid: 4,
                  name: "测评六部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 38,
                  orgId: null,
                  pid: 4,
                  name: "其他测评",
                  orgName: null,
                  children: [
                    {
                      id: 48,
                      orgId: null,
                      pid: 38,
                      name: "测评子部门1",
                      orgName: null,
                      children: [
                        {
                          id: 51,
                          orgId: null,
                          pid: 48,
                          name: "子部门1分部门",
                          orgName: null,
                          children: null,
                        },
                      ],
                    },
                    {
                      id: 49,
                      orgId: null,
                      pid: 38,
                      name: "质量控制部",
                      orgName: null,
                      children: [
                        {
                          id: 50,
                          orgId: null,
                          pid: 49,
                          name: "测评子部门下属2",
                          orgName: null,
                          children: [
                            {
                              id: 52,
                              orgId: null,
                              pid: 50,
                              name: "子部门2分部门",
                              orgName: null,
                              children: null,
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
                {
                  id: 59,
                  orgId: null,
                  pid: 4,
                  name: "其他测评部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 92,
                  orgId: null,
                  pid: 4,
                  name: "安全运维服务部",
                  orgName: null,
                  children: null,
                },
                { id: 96, orgId: null, pid: 4, name: "渗透测试部", orgName: null, children: null },
              ],
            },
            { id: 7, orgId: null, pid: 1, name: "总经办", orgName: null, children: null },
            {
              id: 15,
              orgId: null,
              pid: 1,
              name: "客户服务部",
              orgName: null,
              children: null,
            },
            {
              id: 17,
              orgId: null,
              pid: 1,
              name: "商务中心",
              orgName: null,
              children: [
                {
                  id: 97,
                  orgId: null,
                  pid: 17,
                  name: "商务一部",
                  orgName: null,
                  children: null,
                },
                { id: 98, orgId: null, pid: 17, name: "商务二部", orgName: null, children: null },
              ],
            },
            { id: 34, orgId: null, pid: 1, name: "研发部", orgName: null, children: null },
            {
              id: 35,
              orgId: null,
              pid: 1,
              name: "大客户部",
              orgName: null,
              children: [
                {
                  id: 94,
                  orgId: null,
                  pid: 35,
                  name: "大客户部门子部门1",
                  orgName: null,
                  children: null,
                },
              ],
            },
            {
              id: 36,
              orgId: null,
              pid: 1,
              name: "销售部",
              orgName: null,
              children: [
                {
                  id: 39,
                  orgId: null,
                  pid: 36,
                  name: "销售一部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 40,
                  orgId: null,
                  pid: 36,
                  name: "销售二部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 41,
                  orgId: null,
                  pid: 36,
                  name: "销售三部",
                  orgName: null,
                  children: null,
                },
                { id: 42, orgId: null, pid: 36, name: "培训部", orgName: null, children: null },
              ],
            },
            { id: 90, orgId: null, pid: 1, name: "人事部", orgName: null, children: null },
            {
              id: 101,
              orgId: null,
              pid: 1,
              name: "技术服务中心",
              orgName: null,
              children: [
                {
                  id: 102,
                  orgId: null,
                  pid: 101,
                  name: "等保测评服务部",
                  orgName: null,
                  children: [
                    {
                      id: 108,
                      orgId: null,
                      pid: 102,
                      name: "等保测评一部",
                      orgName: null,
                      children: null,
                    },
                    {
                      id: 109,
                      orgId: null,
                      pid: 102,
                      name: "等保测评二部",
                      orgName: null,
                      children: null,
                    },
                  ],
                },
                {
                  id: 103,
                  orgId: null,
                  pid: 101,
                  name: "安全咨询服务部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 104,
                  orgId: null,
                  pid: 101,
                  name: "渗透测试服务部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 105,
                  orgId: null,
                  pid: 101,
                  name: "安全运维服务部",
                  orgName: null,
                  children: null,
                },
                {
                  id: 106,
                  orgId: null,
                  pid: 101,
                  name: "商密评估服务部",
                  orgName: null,
                  children: null,
                },
                { id: 107, orgId: null, pid: 101, name: "信息系统监理部", orgName: null, children: null },
              ],
            },
            {
              id: 110,
              orgId: null,
              pid: 1,
              name: "营销中心",
              orgName: null,
              children: [
                {
                  id: 111,
                  orgId: null,
                  pid: 110,
                  name: "销售一部",
                  orgName: null,
                  children: null,
                },
                { id: 112, orgId: null, pid: 110, name: "销售二部", orgName: null, children: null },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 3,
      orgId: null,
      pid: 0,
      name: "天帷信息技术（北京）股份有限公司",
      orgName: null,
      children: null,
    },
    {
      id: 93,
      orgId: null,
      pid: 0,
      name: "天帷信息技术（南京）股份有限公司",
      orgName: null,
      children: [
        {
          id: 99,
          orgId: null,
          pid: 93,
          name: "商务中心",
          orgName: null,
          children: [{ id: 100, orgId: null, pid: 99, name: "商务一部", orgName: null, children: null }],
        },
      ],
    },
    { id: 95, orgId: null, pid: 0, name: "江苏翔信信息安全技术有限公司", orgName: null, children: null },
  ],
};
